version: '2'

services:
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_DB=educ
      - POSTGRES_USER=wiaci
      - POSTGRES_PASSWORD=jhq071
    ports:
      - '5432:5432'

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=wiaci
      - SPRING_DATASOURCE_PASSWORD=jhq071
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
